source 'https://rubygems.org'

# Specify your gem's dependencies in stretchysearch-api.gemspec
gemspec

if File.exist? File.expand_path("../../stretchysearch/stretchysearch.gemspec", __FILE__)
  gem 'stretchysearch', :path => File.expand_path("../../stretchysearch", __FILE__), :require => false
end

if File.exist? File.expand_path("../../stretchysearch-transport", __FILE__)
  gem 'stretchysearch-transport', :path => File.expand_path("../../stretchysearch-transport", __FILE__), :require => true
end

if File.exist? File.expand_path("../../stretchysearch-extensions", __FILE__)
  gem 'stretchysearch-extensions', :path => File.expand_path("../../stretchysearch-extensions", __FILE__), :require => false
end
