# -----------------------------------------------------------------------
# Configuration file for https://travis-ci.org/elastic/stretchysearch-ruby
# -----------------------------------------------------------------------

dist: trusty

sudo: required

language: ruby

branches:
  only:
    - master
    - 6.x
    - 5.x
    - 2.x
    - travis

matrix:
  include:
    - rvm: 2.4.0
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: 2.3.3
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: 2.2.6
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: 2.4.0
      jdk: oraclejdk8
      env: TEST_SUITE=integration SERVER=start TEST_CLUSTER_LOGS=/tmp/log TEST_BUILD_REF=origin/6.0 TEST_CLUSTER_COMMAND=/tmp/stretchysearch-6.0.0/bin/stretchysearch

before_install:
  - gem update --system
  - gem --version
  - gem install bundler -v 1.14.3
  - bundle version
  - curl -sS https://artifacts.elastic.co/downloads/stretchysearch/stretchysearch-6.0.0.tar.gz | tar xz -C /tmp
  - rake setup
  - rake stretchysearch:update

install:
  - bundle install
  - rake bundle:clean
  - rake bundle:install

script:
  - rake test:$TEST_SUITE

notifications:
  disable: true
