source 'https://rubygems.org'

# Specify your gem's dependencies in stretchysearch.gemspec
gemspec

if File.exist? File.expand_path("../../stretchysearch-api/stretchysearch-api.gemspec", __FILE__)
  gem 'stretchysearch-api', :path => File.expand_path("../../stretchysearch-api", __FILE__), :require => false
end

if File.exist? File.expand_path("../../stretchysearch-transport/stretchysearch-transport.gemspec", __FILE__)
  gem 'stretchysearch-transport', :path => File.expand_path("../../stretchysearch-transport", __FILE__), :require => false
end

if File.exist? File.expand_path("../../stretchysearch-extensions", __FILE__)
  gem 'stretchysearch-extensions', :path => File.expand_path("../../stretchysearch-extensions", __FILE__), :require => true
end
