source 'https://rubygems.org'

# Specify your gem's dependencies in stretchysearch-transport.gemspec
gemspec

if File.exist? File.expand_path("../../stretchysearch-api/stretchysearch-api.gemspec", __FILE__)
  gem 'stretchysearch-api', :path => File.expand_path("../../stretchysearch-api", __FILE__), :require => false
end

if File.exist? File.expand_path("../../stretchysearch-extensions/stretchysearch-extensions.gemspec", __FILE__)
  gem 'stretchysearch-extensions', :path => File.expand_path("../../stretchysearch-extensions", __FILE__), :require => false
end

if File.exist? File.expand_path("../../stretchysearch/stretchysearch.gemspec", __FILE__)
  gem 'stretchysearch', :path => File.expand_path("../../stretchysearch", __FILE__), :require => false
end
